/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sustainability;

import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author tombr
 */
public class TBOilSpillPage extends javax.swing.JFrame {
    ArrayList <TBOilSpill> slist = new ArrayList<>();
    /**
     * Creates new form OilSpillPage
     */
    public TBOilSpillPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        oilSpillPageBTN = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        turtlesAffectedLBL = new javax.swing.JLabel();
        turtlesAffectedTF = new javax.swing.JTextField();
        dolphinsAffectedLBL = new javax.swing.JLabel();
        dolphinsAffectedTF = new javax.swing.JTextField();
        damageCostsLBL = new javax.swing.JLabel();
        damageCostsTF = new javax.swing.JTextField();
        locationLBL = new javax.swing.JLabel();
        locationTF = new javax.swing.JTextField();
        litresSpiltLBL = new javax.swing.JLabel();
        litresSpiltTF = new javax.swing.JTextField();
        causeOfSpillLBL = new javax.swing.JLabel();
        causeOfSpillTF = new javax.swing.JTextField();
        companyResponsibleLBL = new javax.swing.JLabel();
        companyResponsibleTF = new javax.swing.JTextField();
        pollutionActivitesBTN = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();
        viewBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        oilSpillTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        oilSpillPageBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        oilSpillPageBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oilSpillPageBTN.setText("Oil Spill Page");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(oilSpillPageBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(oilSpillPageBTN)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        turtlesAffectedLBL.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        turtlesAffectedLBL.setText("Turtles Affected");

        dolphinsAffectedLBL.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        dolphinsAffectedLBL.setText("Dolphins Affected");

        damageCostsLBL.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        damageCostsLBL.setText("Damage Costs");

        locationLBL.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        locationLBL.setText("Location");

        litresSpiltLBL.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        litresSpiltLBL.setText("Litres Spilt");

        causeOfSpillLBL.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        causeOfSpillLBL.setText("Cause Of Spill");

        companyResponsibleLBL.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        companyResponsibleLBL.setText("Company Responsible");

        pollutionActivitesBTN.setText("Pollution Activities");
        pollutionActivitesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pollutionActivitesBTNActionPerformed(evt);
            }
        });

        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        viewBTN.setText("VIEW");
        viewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBTNActionPerformed(evt);
            }
        });

        deleteBTN.setText("DELETE");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        oilSpillTA.setColumns(20);
        oilSpillTA.setRows(5);
        jScrollPane1.setViewportView(oilSpillTA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addBTN)
                        .addGap(57, 57, 57)
                        .addComponent(viewBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteBTN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(companyResponsibleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(companyResponsibleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(turtlesAffectedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(turtlesAffectedTF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dolphinsAffectedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(damageCostsLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(litresSpiltLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(litresSpiltTF)
                            .addComponent(dolphinsAffectedTF, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(damageCostsTF)
                            .addComponent(locationTF)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(causeOfSpillLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(causeOfSpillTF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pollutionActivitesBTN)
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(turtlesAffectedTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turtlesAffectedLBL))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dolphinsAffectedLBL)
                    .addComponent(dolphinsAffectedTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(damageCostsLBL)
                    .addComponent(damageCostsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locationLBL)
                    .addComponent(locationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(litresSpiltLBL)
                    .addComponent(litresSpiltTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(causeOfSpillLBL)
                    .addComponent(causeOfSpillTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyResponsibleLBL)
                    .addComponent(companyResponsibleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBTN)
                    .addComponent(viewBTN)
                    .addComponent(deleteBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pollutionActivitesBTN)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pollutionActivitesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pollutionActivitesBTNActionPerformed
        // TODO add your handling code here:
        new TBPollutionActivitiesGUI().setVisible(true);
        this.setVisible(false);
        System.out.println("closed");
        this.dispose();
    }//GEN-LAST:event_pollutionActivitesBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        int turtlesAffected = Integer.parseInt(turtlesAffectedTF.getText());
        int dolphinsAffected = Integer.parseInt(dolphinsAffectedTF.getText());
        int damageCosts = Integer.parseInt(damageCostsTF.getText());
        String location = locationTF.getText();
        int litresSpilt = Integer.parseInt(litresSpiltTF.getText());
        String causeOfSpill = causeOfSpillTF.getText();
        String companyResponsible = companyResponsibleTF.getText();

        // Create a new TBOilSpill object
        //OillSpill wastedPlastic = new WastedPlastic(turtlesAffected, dolphinsAffected, damageCosts, location, amountDumped, typeOfDebris, cleanUpPartner);
        TBOilSpill oilSpill = new TBOilSpill(litresSpilt, causeOfSpill, companyResponsible, turtlesAffected, dolphinsAffected, damageCosts, location);
        
        slist.add(oilSpill);
        
        oilSpillTA.append(oilSpill.toString() + "\n");
    }//GEN-LAST:event_addBTNActionPerformed

    private void viewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBTNActionPerformed
        // TODO add your handling code here:
        oilSpillTA.setText(""); // Clear the text area before appending new content
        if (slist.isEmpty()) {
            oilSpillTA.append("No data to display.\n");
        } else {
            for (TBOilSpill oilSpill : slist) {
                oilSpillTA.append(oilSpill.toString() + "\n\n"); // Assuming TBOilSpill class has a toString() method
            }
        }
    }//GEN-LAST:event_viewBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        if(slist.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nothing in system");
        } else {
            String searchTerm = JOptionPane.showInputDialog(null, "Enter name");
            for(int i = 0; i < slist.size(); i++) {
                TBOilSpill temp = slist.get(i);
                if(temp.getCompanyResponsible().equalsIgnoreCase(searchTerm)){
                    slist.remove(i);
                    JOptionPane.showMessageDialog(null, "It's gone now");
                }
            }
        }
    }//GEN-LAST:event_deleteBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TBOilSpillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TBOilSpillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TBOilSpillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TBOilSpillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TBOilSpillPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel causeOfSpillLBL;
    private javax.swing.JTextField causeOfSpillTF;
    private javax.swing.JLabel companyResponsibleLBL;
    private javax.swing.JTextField companyResponsibleTF;
    private javax.swing.JLabel damageCostsLBL;
    private javax.swing.JTextField damageCostsTF;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JLabel dolphinsAffectedLBL;
    private javax.swing.JTextField dolphinsAffectedTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel litresSpiltLBL;
    private javax.swing.JTextField litresSpiltTF;
    private javax.swing.JLabel locationLBL;
    private javax.swing.JTextField locationTF;
    private javax.swing.JLabel oilSpillPageBTN;
    private javax.swing.JTextArea oilSpillTA;
    private javax.swing.JButton pollutionActivitesBTN;
    private javax.swing.JLabel turtlesAffectedLBL;
    private javax.swing.JTextField turtlesAffectedTF;
    private javax.swing.JButton viewBTN;
    // End of variables declaration//GEN-END:variables
}
